import type { SoldHomeLead } from "@/lib/sold-homes/types";

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const sampleSoldHomes: SoldHomeLead[] = [
  {
    id: "sh-001",
    address: "2847 Lakeview Dr",
    city: "Anaheim",
    state: "CA",
    zip: "92806",
    salePrice: 685000,
    soldDate: daysAgo(2),
    beds: 4,
    baths: 2,
    sqft: 1840,
    propertyType: "single_family",
    daysOnMarket: 6,
    score: 94,
    priority: "hot_now",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-002",
    address: "14512 Walnut Ave",
    city: "Irvine",
    state: "CA",
    zip: "92604",
    salePrice: 1120000,
    soldDate: daysAgo(1),
    beds: 5,
    baths: 3,
    sqft: 2800,
    propertyType: "single_family",
    daysOnMarket: 4,
    score: 92,
    priority: "hot_now",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-003",
    address: "388 Citrus Ln #204",
    city: "Santa Ana",
    state: "CA",
    zip: "92701",
    salePrice: 420000,
    soldDate: daysAgo(3),
    beds: 2,
    baths: 2,
    sqft: 1050,
    propertyType: "condo",
    daysOnMarket: 9,
    score: 81,
    priority: "strong",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-004",
    address: "7203 Maple Canyon Rd",
    city: "Orange",
    state: "CA",
    zip: "92869",
    salePrice: 875000,
    soldDate: daysAgo(4),
    beds: 4,
    baths: 3,
    sqft: 2200,
    propertyType: "single_family",
    daysOnMarket: 14,
    score: 77,
    priority: "strong",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-005",
    address: "921 Harbor Blvd #8",
    city: "Garden Grove",
    state: "CA",
    zip: "92843",
    salePrice: 355000,
    soldDate: daysAgo(5),
    beds: 2,
    baths: 1,
    sqft: 890,
    propertyType: "condo",
    daysOnMarket: 21,
    score: 71,
    priority: "good",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-006",
    address: "1804 Hillcrest Ct",
    city: "Fullerton",
    state: "CA",
    zip: "92833",
    salePrice: 790000,
    soldDate: daysAgo(2),
    beds: 3,
    baths: 2,
    sqft: 1620,
    propertyType: "single_family",
    daysOnMarket: 3,
    score: 89,
    priority: "strong",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-007",
    address: "5540 Crestwood Dr",
    city: "Huntington Beach",
    state: "CA",
    zip: "92649",
    salePrice: 1350000,
    soldDate: daysAgo(6),
    beds: 5,
    baths: 4,
    sqft: 3200,
    propertyType: "single_family",
    daysOnMarket: 8,
    score: 85,
    priority: "strong",
    listingUrl: "https://www.zillow.com/"
  },
  {
    id: "sh-008",
    address: "239 Birch St",
    city: "Brea",
    state: "CA",
    zip: "92821",
    salePrice: 620000,
    soldDate: daysAgo(7),
    beds: 3,
    baths: 2,
    sqft: 1410,
    propertyType: "townhouse",
    daysOnMarket: 11,
    score: 74,
    priority: "good",
    listingUrl: "https://www.zillow.com/"
  }
];
