import type { SoldHomeLead } from "@/lib/sold-homes/types";

function hoursAgo(hours: number) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const sampleSoldHomes: SoldHomeLead[] = [
  {
    id: "sh-001",
    address: "2847 Lakeview Dr",
    city: "Anaheim",
    state: "CA",
    zip: "92806",
    salePrice: 685000,
    soldDate: hoursAgo(3),
    propertyType: "single_family",
    saleType: "estate",
    cashSale: true,
    score: 94,
    priority: "hot_now",
    scoreReason: "Estate sale, cash buyer, 4BR — high cleanout probability.",
    source: "redfin",
    listingUrl: "https://www.redfin.com/",
    agentName: "Sandra Reyes",
    agentPhone: "(714) 555-0182",
    agentEmail: "sreyes@coastalpremier.com",
    agentBrokerage: "Coastal Premier Properties"
  },
  {
    id: "sh-002",
    address: "14512 Walnut Ave",
    city: "Irvine",
    state: "CA",
    zip: "92604",
    salePrice: 1120000,
    soldDate: hoursAgo(7),
    propertyType: "single_family",
    saleType: "trust",
    cashSale: false,
    score: 92,
    priority: "hot_now",
    scoreReason: "Trust sale, 5BR home, fast DOM — estate cleanout likely.",
    source: "homes_com",
    listingUrl: "https://www.homes.com/",
    agentName: "Marcus Lin",
    agentPhone: "(949) 555-0347",
    agentEmail: "mlin@remax-oc.com",
    agentBrokerage: "RE/MAX Fine Homes"
  },
  {
    id: "sh-003",
    address: "1804 Hillcrest Ct",
    city: "Fullerton",
    state: "CA",
    zip: "92833",
    salePrice: 790000,
    soldDate: hoursAgo(19),
    propertyType: "single_family",
    saleType: "as_is",
    cashSale: true,
    score: 89,
    priority: "strong",
    scoreReason: "As-is cash sale — investor flip with cleanout needed.",
    source: "realtor_com",
    listingUrl: "https://www.realtor.com/",
    agentName: "Diane Morel",
    agentPhone: "(714) 555-0629",
    agentEmail: "dmorel@coldwellbanker.com",
    agentBrokerage: "Coldwell Banker Realty"
  },
  {
    id: "sh-004",
    address: "5540 Crestwood Dr",
    city: "Huntington Beach",
    state: "CA",
    zip: "92649",
    salePrice: 1350000,
    soldDate: daysAgo(6),
    propertyType: "single_family",
    saleType: "estate",
    cashSale: false,
    score: 85,
    priority: "strong",
    scoreReason: "Estate sale, large 5BR — substantial junk removal opportunity.",
    source: "redfin",
    listingUrl: "https://www.redfin.com/",
    agentName: "Kevin Tran",
    agentPhone: "(657) 555-0815",
    agentEmail: "ktran@compass.com",
    agentBrokerage: "Compass Real Estate"
  },
  {
    id: "sh-005",
    address: "388 Citrus Ln #204",
    city: "Santa Ana",
    state: "CA",
    zip: "92701",
    salePrice: 420000,
    soldDate: daysAgo(3),
    propertyType: "condo",
    saleType: "foreclosure",
    cashSale: true,
    score: 81,
    priority: "strong",
    scoreReason: "Foreclosure cash sale — likely left-behind contents.",
    source: "homes_com",
    listingUrl: "https://www.homes.com/",
    agentName: "Rosa Gutierrez",
    agentPhone: "(714) 555-0441",
    agentEmail: "rgutierrez@century21.com",
    agentBrokerage: "Century 21 Award"
  },
  {
    id: "sh-006",
    address: "7203 Maple Canyon Rd",
    city: "Orange",
    state: "CA",
    zip: "92869",
    salePrice: 875000,
    soldDate: daysAgo(4),
    propertyType: "single_family",
    saleType: "standard",
    cashSale: false,
    score: 77,
    priority: "strong",
    scoreReason: "4BR quick sale — active realtor worth building relationship.",
    source: "realtor_com",
    listingUrl: "https://www.realtor.com/",
    agentName: "Jason Park",
    agentPhone: "(714) 555-0773",
    agentBrokerage: "Keller Williams Realty"
  },
  {
    id: "sh-007",
    address: "921 Harbor Blvd #8",
    city: "Garden Grove",
    state: "CA",
    zip: "92843",
    salePrice: 355000,
    soldDate: daysAgo(5),
    propertyType: "condo",
    saleType: "investor",
    cashSale: true,
    score: 71,
    priority: "good",
    scoreReason: "Investor cash purchase — flip cleanout possible.",
    source: "homesnap",
    listingUrl: "https://www.homesnap.com/",
    agentName: "Lori Nakamura",
    agentPhone: "(657) 555-0234",
    agentEmail: "lnakamura@bhhscalifornia.com",
    agentBrokerage: "Berkshire Hathaway HomeServices"
  },
  {
    id: "sh-008",
    address: "239 Birch St",
    city: "Brea",
    state: "CA",
    zip: "92821",
    salePrice: 620000,
    soldDate: daysAgo(7),
    propertyType: "townhouse",
    saleType: "as_is",
    cashSale: false,
    score: 74,
    priority: "good",
    scoreReason: "As-is sale, sold over asking — motivated buyers who may need cleanout.",
    source: "redfin",
    listingUrl: "https://www.redfin.com/",
    agentName: "Brian Castillo",
    agentPhone: "(714) 555-0562",
    agentEmail: "bcastillo@exprealty.com",
    agentBrokerage: "eXp Realty of California"
  }
];
